#pragma once
#include "be1/lexer/lex.hpp"
#include "utils/arena.hpp"
#include <variant>
#include <optional>
#include <vector>

namespace beryl::be1 {
  namespace ast {
    // Mostly Generated by Google Gemini
    struct Expr;
    struct Stmt;
    struct TypeNode;

    struct GenericType {
      std::string base_name;
      std::vector<TypeNode*> params;
      std::optional<long> size_const;
    };

    struct TypeNode {
      std::variant<std::string, GenericType> specifier;

      bool is_mut = false;
      bool is_ref = false;
    };

    struct IntLit { int64_t value; };
    struct FloatLit { double value; };
    struct StrLit { std::string value; };
    struct CharLit { char value; };
    struct BoolLit { bool value; };
    struct VarRef { std::string name; };

    struct AddExpr { Expr* left, * right; };
    struct SubExpr { Expr* left, * right; };
    struct MulExpr { Expr* left, * right; };
    struct DivExpr { Expr* left, * right; };
    struct ModExpr { Expr* left, * right; };
    struct EqExpr { Expr* left, * right; };
    struct NotEqExpr { Expr* left, * right; };
    struct LessExpr { Expr* left, * right; };
    struct GreaterExpr { Expr* left, * right; };
    struct AndExpr { Expr* left, * right; };
    struct OrExpr { Expr* left, * right; };

    struct NormalAssign { Expr* target; Expr* value; };
    struct AddAssign { Expr* target; Expr* value; };
    struct SubAssign { Expr* target; Expr* value; };
    struct MulAssign { Expr* target; Expr* value; };
    struct DivAssign { Expr* target; Expr* value; };
    struct ModAssign { Expr* target; Expr* value; };

    struct ArrayAccess { Expr* array; Expr* index; bool is_at; };
    struct CastExpr { Expr* expr; TypeNode* to; bool unsafe; };
    struct CallExpr { std::string name; std::vector<Expr*> args; };
    struct UnaryExpr { Token op; Expr* operand; };

    struct Expr {
      std::variant<
        IntLit, FloatLit, StrLit, CharLit, BoolLit, VarRef,
        AddExpr, SubExpr, MulExpr, DivExpr, ModExpr,
        EqExpr, NotEqExpr, LessExpr, GreaterExpr, AndExpr, OrExpr,
        NormalAssign, AddAssign, SubAssign, MulAssign, DivAssign, ModAssign,
        ArrayAccess, CastExpr, CallExpr, UnaryExpr
      > data;
    };

    struct Block { std::vector<Stmt*> body; };

    struct VarDecl {
      std::string name;
      std::optional<TypeNode*> type;
      std::optional<Expr*> init;
    };

    struct CondBlock {
      Expr* cond;
      Block* body;
    };
    struct IfStmt {
      Expr* cond;
      Block* then_b;
      std::vector<CondBlock> else_if_bs;
      std::optional<Block*> else_b;
    };
    struct TernaryExpr { Expr* cond; Expr* then_e; Expr* else_e; };
    struct WhileLoop { Expr* cond; Block* body; bool is_do; };
    struct ForLoop { std::variant<VarDecl*, Expr*> init; Expr* cond; Expr* step; Block* body; };
    struct ForEach { std::string var; Expr* container; Block* body; };
    struct RepeatLoop { Expr* count; Block* body; };
    struct WaitStmt { Expr* cond; };
    struct ExitStmt { Expr* code; };
    struct ReturnStmt { std::optional<Expr*> val; };

    struct Stmt {
      std::variant<
        VarDecl, IfStmt, TernaryExpr, WhileLoop, ForLoop, ForEach,
        RepeatLoop, WaitStmt, ExitStmt, ReturnStmt, Block, Expr*
      > data;
    };

    struct Parameter {
      std::string name;
      TypeNode* type;
      std::optional<Expr*> default_val;
    };

    struct FunctionDecl {
      std::string name;
      std::vector<Parameter> params;
      std::optional<TypeNode*> ret_type;
      Block* body;
    };

    struct NamespaceDecl {
      std::string name;
      std::vector<std::variant<FunctionDecl*, VarDecl*, NamespaceDecl*>> members;
    };

    struct ImportDecl {
      std::string module_name;
      std::vector<std::string> entities;
    };

    struct Program {
      std::vector<std::variant<FunctionDecl, VarDecl, NamespaceDecl, ImportDecl>> body;
    };
  }

  ast::Program* parse(TokenStream& tokens, Arena& arena);
}